# Generated by Django 5.2.6 on 2025-09-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('terms', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('id_card', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('license', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('graduation_certificate', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('internship_certificate', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('sgk_report', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('criminal_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('criminal_record_de', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('family_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('formul_a', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('formul_b', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
