# Generated by Django 5.1.1 on 2025-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='birth_date',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='criminal_record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='criminal_record_de',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='education',
            field=models.CharField(choices=[('primary', 'İlkokul'), ('middle', 'Ortaokul'), ('highschool', 'Lise'), ('associate', 'Ön Lisans'), ('bachelor', 'Lisans'), ('master', 'Yüksek Lisans'), ('phd', 'Doktora')], max_length=20, verbose_name='Eğitim Durumu'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='family_record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='formul_a',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='formul_b',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='internship_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='Uyruk'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Gizlilik Politikası'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='profession',
            field=models.CharField(choices=[('kamyon_surucu', 'Kamyon Şoförü'), ('tir_surucu', 'Tır Şoförü'), ('kurye', 'Kurye'), ('saglik', 'Sağlık'), ('elektrik', 'Elektrik'), ('tekniker', 'Tekniker'), ('muhendis', 'Mühendis'), ('ogretmen', 'Öğretmen'), ('diger', 'Diğer')], max_length=50, verbose_name='Meslek'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='sgk_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Kullanım Koşulları'),
        ),
    ]
