# Generated by Django 5.1.1 on 2025-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_userform_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Ek Belgeler'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='criminal_record',
            field=models.FileField(blank=True, null=True, upload_to='records/', verbose_name='Adli Sicil Kaydı'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='criminal_record_de',
            field=models.FileField(blank=True, null=True, upload_to='records/', verbose_name='Almanya Adli Sicil Kaydı'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/', verbose_name='Diploma'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='family_record',
            field=models.FileField(blank=True, null=True, upload_to='records/', verbose_name='Aile Kaydı'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='formul_a',
            field=models.FileField(blank=True, null=True, upload_to='forms/', verbose_name='Formül A'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='formul_b',
            field=models.FileField(blank=True, null=True, upload_to='forms/', verbose_name='Formül B'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Mezuniyet Belgesi'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/', verbose_name='Kimlik Kartı'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='internship_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Staj Belgesi'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='Ehliyet'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='sgk_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='SGK Raporu'),
        ),
    ]
