# Generated by Django 5.1.1 on 2025-10-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_userform_additional_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='criminal_record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='criminal_record_de',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='family_record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='formul_a',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='formul_b',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='internship_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='sgk_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
