# Generated by Django 5.1.1 on 2025-10-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_alter_userform_additional_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='nationality',
        ),
        migrations.AddField(
            model_name='userform',
            name='source',
            field=models.CharField(choices=[('ads', 'Sosyal medya reklamları veya diğer reklamlar'), ('friend', 'Bir tanıdığın vasıtası üzerine'), ('google', 'Google'), ('other', 'Diğer')], default='orher', max_length=200, verbose_name='Nereden Ulaştı'),
            preserve_default=False,
        ),
    ]
