# Generated by Django 5.1.1 on 2025-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_remove_userform_nationality_userform_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='source',
            field=models.CharField(choices=[('Sosyal medya', 'Sosyal medya reklamları veya diğer reklamlar'), ('Bir tandığın vasıtasıyla', 'Bir tanıdığın vasıtası üzerine'), ('Google', 'Google'), ('Diper', 'Diğer')], max_length=200, verbose_name='Nereden Ulaştı'),
        ),
    ]
