# Generated by Django 5.1.1 on 2025-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_userform_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='criminal_record',
            new_name='adli_sicil',
        ),
        migrations.RenameField(
            model_name='userform',
            old_name='criminal_record_de',
            new_name='adli_sicil_almanca',
        ),
        migrations.RenameField(
            model_name='userform',
            old_name='additional_documents',
            new_name='ek_belgeler',
        ),
        migrations.RenameField(
            model_name='userform',
            old_name='graduation_certificate',
            new_name='mezuniyet_sertifikasi',
        ),
        migrations.RenameField(
            model_name='userform',
            old_name='sgk_report',
            new_name='sgk_hizmet_dokumu',
        ),
        migrations.RenameField(
            model_name='userform',
            old_name='family_record',
            new_name='vukuatli_nufus_kayit_ornegi',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='internship_certificate',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='license',
        ),
        migrations.AddField(
            model_name='userform',
            name='ehliyet',
            field=models.FileField(blank=True, null=True, upload_to='ehliyets/'),
        ),
        migrations.AddField(
            model_name='userform',
            name='kimlik_karti',
            field=models.FileField(blank=True, null=True, upload_to='kimlik_kartis/'),
        ),
        migrations.AddField(
            model_name='userform',
            name='staj_sertifikasi',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='source',
            field=models.CharField(choices=[('ads', 'Sosyal medya reklamları veya diğer reklamlar'), ('friend', 'Bir tanıdığın vasıtası üzerine'), ('google', 'Google'), ('other', 'Diğer')], max_length=200, verbose_name='Nereden Ulaştı'),
        ),
    ]
