# Generated by Django 5.1.1 on 2025-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_rename_criminal_record_userform_adli_sicil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='ikametgah',
            field=models.FileField(blank=True, null=True, upload_to='ikametgahs/'),
        ),
    ]
